apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: spring-petclinic
spec:
  selector:
    app: spring-petclinic
  replicas: 1
  template:
    metadata:
      labels:
        app: spring-petclinic
    spec:
      containers:
        - name: cicd
          image: openshift/spring-petclinic:latest
          ports:
            - containerPort: 8080