apiVersion: route.openshift.io/v1
kind: Route
metadata:
  labels:
    {{ include "app.labels" . | nindent 4 }}
  name: {{ include "app.fullname" . }}
spec:
  port:
    targetPort: 8080-tcp
  to:
    kind: Service
    name: {{ include "app.fullname" . }}
    weight: 100